version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.20.1
  working_directory: ~/blog

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test --runInBand --no-cache

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:coverage --runInBand --no-cache
      - save_cache:
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage

  codecov:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - coverage-output-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn global add codecov
      - run: yarn codecov

  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "79:b1:6f:74:c1:77:23:fc:cb:79:ff:69:3c:60:01:6b"
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          command: |
            git config user.email "amoseui@gmail.com"
            git config user.name "Amos Lim"
            npm run deploy

workflows:
  version: 2
  test:
    jobs:
      - install:
          branches:
            ignore:
              - gh-pages
      - lint:
          requires:
            - install
          branches:
            ignore:
              - gh-pages
      - test:
          requires:
            - install
          branches:
            ignore:
              - gh-pages
      - coverage:
          requires:
            - install
          branches:
            ignore:
              - gh-pages
      - codecov:
          requires:
            - coverage
          branches:
            ignore:
              - gh-pages
      - deploy:
          requires:
            - install
          #branches:
              #only:
              #- master
